name: flutter_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 颜色组件
  flutter_color_plugin: ^0.0.2
  # 跳转到其它应用，或者是打开其它应用的一个组件或者是插件
  url_launcher: ^5.4.2
  # 图片选择和拍照的插件,image_picker它是用到了一个AndroidX的一个兼容库，所有必须要引入androidX
  # 但是由于这个项目在创建的时候就已经配置了androidX，所以它不需要配置。
  image_picker: ^0.6.3+4
  #  path_provider 负责查找 iOS/Android 的目录文件
  path_provider: ^1.6.1
  # 从内存、本地资源加载，可以使用transparent_image
  transparent_image: ^1.0.0
  # 从网络上加载图片，然后将这个图片缓存到本地
  cached_network_image: ^2.0.0
  # 轮播图组件
  flutter_swiper: ^1.1.6
  # 网络请求插件
  http: ^0.12.0+4
  # 本地存储
  shared_preferences: ^0.5.6+2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # 注意：这个地方assets前面不能有空格
  assets:
    - images/test.png
    - data/home_page.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: RubikMonoOne # 定义字体的名字，随便起
      fonts:
        - asset: fonts/RubikMonoOne-Regular.ttf # 定义字体的路径
    - family: iconFont # 定义字体的名字，随便起
      fonts:
        - asset: fonts/iconfont.ttf # 定义字体的路径